############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "News"
url = "news/"
weight = 3

[[main]]
name = "Varieties"
url = "varieties/"
weight = 3

[[main]]
name = "Literature"
url = "literature/"
weight = 3

[[main]]
name = "Resource"
url = "resource/"
weight = 3


# footer menu


